name: cap
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py36h8c4c3a4_1
  - asciitree=0.3.3=py_2
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py36h8c4c3a4_1000
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36h9f0ad1d_1007
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1=py36h45558ae_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.27.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - enum34=1.1.10=py36h9f0ad1d_1
  - expat=2.2.9=he1b5a44_2
  - fasteners=0.14.1=py_3
  - fire=0.3.1=pyh9f0ad1d_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs-lite=2019.12.3=py36h785e9b2_1
  - imageio=2.9.0=py_0
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h95af2a2_0
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.1=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.2.0=py36hdb11119_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_16
  - liblapack=3.8.0=16_mkl
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - markupsafe=1.1.1=py36h8c4c3a4_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py36h5ffbc53_0
  - mistune=0.8.4=py36h8c4c3a4_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - monotonic=1.5=py_0
  - msgpack-python=1.0.0=py36hdb11119_1
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.5=py36h9f0ad1d_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.0=py_1
  - networkx=2.5=py_0
  - ninja=1.10.1=py36hfd86e86_0
  - notebook=6.1.4=py36h9f0ad1d_0
  - numcodecs=0.7.2=py36h831f99a_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - pathlib=1.0.1=py36h9f0ad1d_2
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.2.2=py36_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py36hcca6a23_4
  - pyrsistent=0.17.3=py36h8c4c3a4_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.6.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pywavelets=1.1.1=py36h68bb277_2
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - pyzmq=19.0.2=py36h9947dbf_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - scikit-image=0.17.2=py36h7c3b610_2
  - scikit-learn=0.23.2=py36hfb379a7_0
  - scipy=1.5.2=py36h3a855aa_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py36_0
  - simplegeneric=0.8.1=py_1
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - termcolor=1.1.0=py_2
  - terminado=0.9.1=py36h9f0ad1d_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2019.7.26.2=py36_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.7.0=py36_cu102
  - tornado=6.0.4=py36h8c4c3a4_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py36h9f0ad1d_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zarr=2.4.0=py_0
  - zeromq=4.3.2=he1b5a44_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
